### ISSUE TITLE
When a failed snapshot is invalidated, it triggers infinite retries

### ISSUE THREAD

**Issue by ericaprieto** [jamesknelson/react-zen#2]
If the request fails and the snapshot is invalidated (to trigger a retry), the request will be retried until it stops failing.

Is this the right way to trigger retries?

Sample: https://codesandbox.io/s/sad-turing-0qi9s

**Comment by jamesknelson** [comment]
Thanks for pointing this out! Yeah - the design for this particular library was a *teensy* bit out. There needs to be a better way to trigger requests and expires -- that's my goal with the `Resource` model from retil:

https://github.com/jamesknelson/retil/blob/master/src/models/resource/resource.ts

It's basically a rewrite of this library with a few extra features, and which solves this problem. There's no docs yet, but I just got the first tests passing and am planning on using it in a production app, so there should be more progress on the coming weeks.
